import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

export interface ArtEntry { pack: string; url: string; w: number; h: number; meta?: Record<string, unknown> }
export type ArtManifest = Record<string, ArtEntry>;

export const ROOT = join(import.meta.dirname, '..', '..');
const JSON_PATH = join(ROOT, 'src', 'assets', 'art-manifest.json');
const TS_PATH = join(ROOT, 'src', 'assets', 'manifest.generated.ts');

export function loadManifest(): ArtManifest {
  return existsSync(JSON_PATH) ? (JSON.parse(readFileSync(JSON_PATH, 'utf8')) as ArtManifest) : {};
}

export function saveManifest(m: ArtManifest): void {
  const sorted = Object.fromEntries(Object.entries(m).sort(([a], [b]) => a.localeCompare(b)));
  writeFileSync(JSON_PATH, JSON.stringify(sorted, null, 1));
  writeFileSync(
    TS_PATH,
    `// GENERATED by tools/art-import — do not edit by hand.\nimport data from './art-manifest.json';\n` +
      `export interface ArtEntry { pack: string; url: string; w: number; h: number; meta?: Record<string, unknown> }\n` +
      `export const ART = data as unknown as Record<string, ArtEntry>;\nexport type ArtKey = keyof typeof data;\n`,
  );
}
