using System;
using Assets.Scripts.Network.HandlerBase;
using Assets.Scripts.Network.IncomingPacketHandlers;
using Assets.Scripts.Network.IncomingPacketHandlers.Market;
using Assets.Scripts.Network.IncomingPacketHandlers.Trading;
using Assets.Scripts.PlayerControl;
using RebuildSharedData.Networking;

namespace Assets.Scripts.Network.PacketBase
{
    public static partial class ClientPacketHandler
    {
        //Not readonly: the table is generated by an editor menu item, and when that has
        //not been run the array is shorter than the packet list. Init grows it rather
        //than leaving every packet added since then with nowhere to go.
        private static ClientPacketHandlerBase[] handlers;

        /// <summary>
        /// Whether this packet has somewhere to go.
        ///
        /// Less than the length, not less than or equal: the guard is the only thing
        /// standing between a packet number the table does not reach and an index off the
        /// end of it, and off by one here throws inside the receive loop rather than
        /// ignoring one packet. The table is shorter than the enum whenever a handler has
        /// been added and the generator has not been run, which is exactly when this
        /// matters.
        /// </summary>
        public static bool HasValidHandler(PacketType type) =>
            (int)type >= 0 && (int)type < handlers.Length
            && handlers[(int)type].GetType() != typeof(InvalidPacket);

        public static void Execute(PacketType type, ClientInboundMessage msg) => handlers[(int)type].ReceivePacket(msg);
        
        /// <summary>
        /// The handlers this file knows about by hand, for when the generated table does
        /// not have them yet.
        ///
        /// The table is written by an editor menu item and nothing runs that
        /// automatically, so between adding a handler and remembering to regenerate, the
        /// packet it answers arrives and goes nowhere - which looks exactly like the
        /// server never answering, and cost two rounds of looking in the wrong place.
        ///
        /// A slot the table already fills is left alone, so this shrinks to nothing the
        /// moment somebody regenerates. It is not a second dispatch table; it is the list
        /// of things the first one might be behind on.
        /// </summary>
        private static readonly (PacketType Type, Func<ClientPacketHandlerBase> Make)[] LateAdditions =
        {
            (PacketType.TradeUpdate, () => new PacketTradeUpdate()),
            (PacketType.InboxData, () => new PacketInboxData()),
            (PacketType.AuctionData, () => new PacketAuctionData()),
        };

        /// <summary>
        /// Grows the table to the size of the packet list and fills anything the list
        /// above knows how to fill. Says what it had to do, so a table that keeps needing
        /// this is a table somebody notices.
        /// </summary>
        private static void Repair()
        {
            var known = System.Enum.GetNames(typeof(PacketType)).Length;

            if (handlers.Length < known)
            {
                var grown = new ClientPacketHandlerBase[known];
                Array.Copy(handlers, grown, handlers.Length);
                for (var i = handlers.Length; i < known; i++)
                    grown[i] = new InvalidPacket();

                UnityEngine.Debug.LogWarning($"[Packets] the generated table held {handlers.Length} "
                    + $"slots for {known} packet types and has been grown to fit. Run "
                    + "Ragnarok > CodeGen > Update Packet Handlers to make that permanent.");
                handlers = grown;
            }

            var filled = 0;
            foreach (var (type, make) in LateAdditions)
            {
                var slot = (int)type;
                if (slot < 0 || slot >= handlers.Length)
                    continue;
                if (handlers[slot].GetType() != typeof(InvalidPacket))
                    continue; //the table has it, and the table wins

                handlers[slot] = make();
                filled++;
            }

            if (filled > 0)
                UnityEngine.Debug.LogWarning($"[Packets] {filled} handler(s) the generated table "
                    + "did not have were filled in by hand.");
            else
                UnityEngine.Debug.Log($"[Packets] handler table ready: {handlers.Length} slots.");
        }

        public static void Init(NetworkManager network, PlayerState state)
        {
            Repair();

            for (var i = 0; i < handlers.Length; i++)
            {
                handlers[i].Network = network;
                handlers[i].Camera = CameraFollower.Instance;
                handlers[i].UiManager = UiManager.Instance;
                handlers[i].State = state;
            }
        }
    }
}