// GENERATED by tools/art-import — do not edit by hand.
import data from './art-manifest.json';
export interface ArtEntry { pack: string; url: string; w: number; h: number; meta?: Record<string, unknown> }
export const ART = data as unknown as Record<string, ArtEntry>;
export type ArtKey = keyof typeof data;
